using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace Xt30Probe.Presentation
{
    // Traduction de l'interface.
    //
    // La CLÉ est le texte anglais lui-même : une chaîne non traduite s'affiche donc
    // en anglais correct au lieu de laisser un identifiant technique à l'écran.
    // La traduction est faite au moment du dessin, jamais à la construction des
    // contrôles : changer de langue rafraîchit l'application sans la redémarrer.
    //
    // Les VALEURS de réglage (Off, Weak, Strong, Daylight, DR400…) ne sont jamais
    // traduites : elles sont écrites telles quelles dans la bibliothèque et lues par
    // les encodeurs du fichier de réglages. Les traduire casserait le transfert.
    public static class Strings
    {
        public static readonly string[] Available = { "en", "fr", "es", "de", "it" };

        public static string DisplayName(string code)
        {
            switch (code)
            {
                case "fr": return "Français";
                case "es": return "Español";
                case "de": return "Deutsch";
                case "it": return "Italiano";
                default: return "English";
            }
        }

        static Dictionary<string, string> _map;
        static string _current = "en";
        static string _file;
        public static event EventHandler Changed;
        public static string Current { get { return _current; } }

        public static string T(string english)
        {
            if (_map == null || english == null) return english;
            string value;
            return _map.TryGetValue(english, out value) ? value : english;
        }

        public static string T(string english, params object[] args)
        {
            try { return string.Format(T(english), args); }
            catch (FormatException) { return T(english); }
        }

        // Langue choisie par l'utilisateur ; à défaut celle de Windows si elle est
        // couverte, sinon l'anglais.
        public static void Load(string dataDirectory)
        {
            _file = Path.Combine(dataDirectory ?? ".", "language.txt");
            string code = null;
            try { if (File.Exists(_file)) code = File.ReadAllText(_file).Trim().ToLowerInvariant(); }
            catch (Exception) { }
            if (Array.IndexOf(Available, code) < 0)
            {
                try { code = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant(); }
                catch (Exception) { code = "en"; }
                if (Array.IndexOf(Available, code) < 0) code = "en";
            }
            Apply(code);
        }

        public static void Use(string code)
        {
            if (Array.IndexOf(Available, code) < 0 || code == _current) return;
            Apply(code);
            try { if (_file != null) { Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(_file))); File.WriteAllText(_file, code); } }
            catch (Exception) { }
            if (Changed != null) Changed(null, EventArgs.Empty);
        }

        static void Apply(string code)
        {
            _current = code;
            switch (code)
            {
                case "fr": _map = French(); break;
                case "es": _map = Spanish(); break;
                case "de": _map = German(); break;
                case "it": _map = Italian(); break;
                default: _map = null; break;
            }
            // Écran d'accueil et libellés de la page Appareil, ajoutés séparément
            // pour garder les tables principales lisibles.
            if (_map != null) foreach (KeyValuePair<string, string> pair in Extra(code)) _map[pair.Key] = pair.Value;
        }

        static Dictionary<string, string> Build(string[] pairs)
        {
            Dictionary<string, string> map = new Dictionary<string, string>();
            for (int i = 0; i + 1 < pairs.Length; i += 2) map[pairs[i]] = pairs[i + 1];
            return map;
        }

        // Étapes du didacticiel et libellés de la page Appareil.
        // Une chaîne absente d'une langue s'affiche en anglais : c'est volontaire,
        // mieux vaut une phrase juste en anglais qu'une traduction inventée.
        static Dictionary<string, string> Extra(string code)
        {
            switch (code)
            {
                case "fr": return Build(new string[] {
                    "SOURCE", "SOURCE",
                    "DEMONSTRATION RECIPE", "RECETTE DE DÉMONSTRATION",
                    "YOUR LIBRARY", "VOTRE BIBLIOTHÈQUE",
                    "Camera bank", "Banque de l'appareil",
                    "Video recipe", "Recette vidéo",
                    "Imported recipe", "Recette importée",
                    "Local recipe", "Recette locale",
                    "Disconnected", "Déconnecté",
                    "USB mode\nnot reported", "Mode USB\nnon communiqué",
                    "Looking for camera…", "Recherche de l'appareil…",
                    "Last scan data · camera is not connected", "Données de la dernière lecture · appareil non connecté",
                    "USB mode not reported by the camera", "Mode USB non communiqué par l'appareil",
                    "Model", "Modèle", "Firmware", "Micrologiciel", "USB Mode", "Mode USB",
                    "VID / PID", "VID / PID", "Protocol", "Protocole", "Status", "État",
                    "Not reported", "Non communiqué", "Not scanned", "Non lu", "Waiting for camera", "En attente de l'appareil",
                    "ACTIONS", "ACTIONS",
                    "Quick Help", "Aide rapide",
                    // Menu du boîtier, tel qu'il s'affiche sur un X-T30 en français
                    "SET UP", "CONFIG.",
                    "CONNECTION SETTING", "RÉGLAGE CONNEXION",
                    "USB CONNECTION MODE", "MODE CONNEXION USB",
                    "USB RAW CONV./\nBACKUP RESTORE", "CONV. RAW USB /\nSAUVEG. RESTAUR.",
                    // États rapportés par le moteur de lecture
                    "Connected", "Connecté", "Scanning camera…", "Lecture de l'appareil…",
                    "Communication error", "Erreur de communication",
                    "Looking for your camera…", "Recherche de votre appareil…",
                    "Connect your camera", "Branchez votre appareil", "Ready to scan", "Prêt pour la lecture",
                    "Camera disconnected. Connect your X-T30 to get started.", "Appareil déconnecté. Branchez votre X-T30 pour commencer.",
                    "Camera connected. Ready for a read-only scan.", "Appareil connecté. Prêt pour une lecture seule.",
                    "Scanning · read only", "Lecture · seule lecture",
                    "Scanning camera. Reading properties only…", "Lecture de l'appareil. Propriétés uniquement…",
                    "Camera scan completed successfully.", "Lecture de l'appareil terminée.",
                    "Detection error", "Erreur de détection",
                    "Offline UI preview · no camera accessed", "Aperçu hors ligne · aucun accès à l'appareil",
                    "Scan ended, but the report could not be loaded. View Diagnostics.",
                        "Lecture terminée, mais le rapport n'a pas pu être chargé. Voir le diagnostic.",
                    "For full communication with your X-T30, please set the USB CONNECTION MODE to:",
                        "Pour communiquer pleinement avec votre X-T30, réglez le MODE DE CONNEXION USB sur :",
                    "Then turn the camera off and on again.", "Éteignez puis rallumez l'appareil.",
                    "Scan Camera", "Analyser l'appareil", "Scanning…", "Analyse en cours…",
                    "Open TXT Report", "Ouvrir le rapport TXT", "Open JSON Report", "Ouvrir le rapport JSON",
                    "Open Reports Folder", "Ouvrir le dossier des rapports",
                    "Imported from a public recipe article. Values are shown exactly as published; missing values stay unspecified.",
                        "Importée d'un article public de recettes. Les valeurs sont affichées telles que publiées ; celles qui manquent restent non précisées.",
                    "Example values for this interface — not an authenticated recipe.",
                        "Valeurs d'exemple pour cette interface — ce n'est pas une recette authentifiée.",
                    "Exactly 7 recipes per pack · one file loads all seven banks at once",
                        "Exactement 7 recettes par pack · un seul fichier charge les sept banques",
                    "Load Pack to Camera", "Charger le pack dans l'appareil",
                    "Create camera file for this pack…", "Créer le fichier pour ce pack…",
                    // Didacticiel
                    "Welcome to XT30 Recipe Manager", "Bienvenue dans XT30 Recipe Manager",
                    "This application keeps your film recipes on this computer and loads them into the C1-C7 custom banks of your Fujifilm X-T30.\n\nIt never sends a write command to the camera. When you send recipes, the file is written by Fujifilm's own Tether App, exactly as if you had loaded it yourself.",
                        "Cette application garde vos recettes de simulation de film sur cet ordinateur et les charge dans les banques personnalisées C1-C7 de votre Fujifilm X-T30.\n\nElle n'envoie jamais de commande d'écriture à l'appareil. Quand vous envoyez des recettes, le fichier est écrit par la Tether App de Fujifilm, exactement comme si vous l'aviez chargé vous-même.",
                    "1 · Put the camera in the right USB mode", "1 · Mettez l'appareil dans le bon mode USB",
                    "On the camera:\n\nMENU → SET UP → CONNECTION SETTING → USB CONNECTION MODE → USB RAW CONV./BACKUP RESTORE\n\nThen turn the camera off and on again, and connect it with the USB cable. Without this mode the camera behaves like a card reader and its settings stay out of reach.",
                        "Sur l'appareil :\n\nMENU → CONFIG. → RÉGLAGE CONNEXION → MODE CONNEXION USB → CONV. RAW USB / SAUVEG. RESTAUR.\n\nÉteignez puis rallumez l'appareil, et branchez le câble USB. Sans ce mode, l'appareil se comporte comme un lecteur de carte et ses réglages restent inaccessibles.",
                    "2 · Read your camera", "2 · Lisez votre appareil",
                    "Open Camera Slots and press \"Read my camera\".\n\nThe seven banks are copied from the camera and decoded. Only what the camera actually stores is displayed; anything it does not store stays marked as not specified, never guessed.",
                        "Ouvrez Banques C1-C7 et appuyez sur « Lire mon appareil ».\n\nLes sept banques sont copiées depuis l'appareil puis décodées. Seul ce que l'appareil stocke réellement est affiché ; ce qu'il ne stocke pas reste marqué comme non précisé, jamais deviné.",
                    "3 · Find or create a recipe", "3 · Trouvez ou créez une recette",
                    "The Recipes page holds your own recipes plus the imported catalogues, filtered by film simulation, category, compatibility or favourites.\n\n\"New Recipe\" creates your own. Only values your X-T30 really accepts are offered, so a recipe made here is always transferable. Choose Photo for the C1-C7 banks, or Video for the movie mode.",
                        "La page Recettes réunit vos recettes et les catalogues importés, filtrables par simulation de film, catégorie, compatibilité ou favoris.\n\n« Nouvelle recette » crée la vôtre. Seules les valeurs que votre X-T30 accepte vraiment sont proposées : une recette créée ici est toujours transférable. Choisissez Photo pour les banques C1-C7, ou Vidéo pour le mode film.",
                    "4 · Load recipes into C1-C7", "4 · Chargez des recettes dans C1-C7",
                    "In Camera Slots, press \"Load recipes into C1-C7…\", pick a recipe per bank and send.\n\nAll seven banks travel in a single file, so the camera is updated in one restore. Banks you leave unchanged, and every other camera setting, are untouched.",
                        "Dans Banques C1-C7, appuyez sur « Charger des recettes dans C1-C7… », choisissez une recette par banque et envoyez.\n\nLes sept banques voyagent dans un seul fichier : l'appareil est mis à jour en une seule restauration. Les banques laissées inchangées, et tous les autres réglages, ne sont pas touchés.",
                    "5 · What the camera cannot store", "5 · Ce que l'appareil ne peut pas stocker",
                    "The camera's settings file has no room for ISO, for the white balance shift, or for a few values with no verified code.\n\nThe application never invents them: it lists them after each send so you can set them in the camera menu. The white balance shift is written into the bank name instead, which is why names look like \"PACIFIC R+1 B-3\".\n\nKeep your original settings file: it restores the camera exactly as it was.",
                        "Le fichier de réglages de l'appareil n'a pas de place pour l'ISO, pour le décalage de balance des blancs, ni pour quelques valeurs dont le code n'est pas vérifié.\n\nL'application ne les invente jamais : elle les liste après chaque envoi pour que vous les régliez dans le menu du boîtier. Le décalage de balance des blancs est écrit dans le nom de la banque : c'est pourquoi les noms ressemblent à « PACIFIC R+1 B-3 ».\n\nConservez votre fichier de réglages d'origine : il remet l'appareil exactement dans son état initial.",
                });
                case "es": return Build(new string[] {
                    "Disconnected", "Desconectada",
                    "Looking for camera…", "Buscando la cámara…",
                    "Model", "Modelo", "Firmware", "Firmware", "USB Mode", "Modo USB",
                    "Protocol", "Protocolo", "Status", "Estado",
                    "Not reported", "No indicado", "Not scanned", "Sin leer", "Waiting for camera", "Esperando la cámara",
                    "ACTIONS", "ACCIONES", "Quick Help", "Ayuda rápida",
                    "Scan Camera", "Analizar la cámara", "Scanning…", "Analizando…",
                    "Welcome to XT30 Recipe Manager", "Bienvenido a XT30 Recipe Manager",
                    "1 · Put the camera in the right USB mode", "1 · Ponga la cámara en el modo USB correcto",
                    "2 · Read your camera", "2 · Lea su cámara",
                    "3 · Find or create a recipe", "3 · Busque o cree una receta",
                    "4 · Load recipes into C1-C7", "4 · Cargue recetas en C1-C7",
                    "5 · What the camera cannot store", "5 · Lo que la cámara no puede guardar",
                });
                case "de": return Build(new string[] {
                    "Disconnected", "Getrennt",
                    "Looking for camera…", "Suche die Kamera…",
                    "Model", "Modell", "Firmware", "Firmware", "USB Mode", "USB-Modus",
                    "Protocol", "Protokoll", "Status", "Status",
                    "Not reported", "Nicht gemeldet", "Not scanned", "Nicht ausgelesen", "Waiting for camera", "Warte auf die Kamera",
                    "ACTIONS", "AKTIONEN", "Quick Help", "Schnellhilfe",
                    "Scan Camera", "Kamera analysieren", "Scanning…", "Analysiere…",
                    "Welcome to XT30 Recipe Manager", "Willkommen bei XT30 Recipe Manager",
                    "1 · Put the camera in the right USB mode", "1 · Stellen Sie den richtigen USB-Modus ein",
                    "2 · Read your camera", "2 · Kamera auslesen",
                    "3 · Find or create a recipe", "3 · Rezept finden oder anlegen",
                    "4 · Load recipes into C1-C7", "4 · Rezepte in C1-C7 laden",
                    "5 · What the camera cannot store", "5 · Was die Kamera nicht speichern kann",
                });
                case "it": return Build(new string[] {
                    "Disconnected", "Scollegata",
                    "Looking for camera…", "Ricerca della fotocamera…",
                    "Model", "Modello", "Firmware", "Firmware", "USB Mode", "Modalità USB",
                    "Protocol", "Protocollo", "Status", "Stato",
                    "Not reported", "Non indicato", "Not scanned", "Non letta", "Waiting for camera", "In attesa della fotocamera",
                    "ACTIONS", "AZIONI", "Quick Help", "Aiuto rapido",
                    "Scan Camera", "Analizza la fotocamera", "Scanning…", "Analisi in corso…",
                    "Welcome to XT30 Recipe Manager", "Benvenuto in XT30 Recipe Manager",
                    "1 · Put the camera in the right USB mode", "1 · Imposta la modalità USB corretta",
                    "2 · Read your camera", "2 · Leggi la fotocamera",
                    "3 · Find or create a recipe", "3 · Trova o crea una ricetta",
                    "4 · Load recipes into C1-C7", "4 · Carica ricette in C1-C7",
                    "5 · What the camera cannot store", "5 · Ciò che la fotocamera non può salvare",
                });
                default: return new Dictionary<string, string>();
            }
        }

        static Dictionary<string, string> French()
        {
            return Build(new string[] {
                // Navigation et bandeau
                "Camera", "Appareil photo",
                "Recipes", "Recettes",
                "Camera Slots", "Banques C1-C7",
                "Packs", "Packs",
                "Backups", "Sauvegardes",
                "Diagnostics", "Diagnostic",
                "Settings", "Réglages",
                "READ ONLY", "LECTURE SEULE",
                "View Diagnostics", "Voir le diagnostic",
                "Last scan: {0}", "Dernière lecture : {0}",
                "Waiting for camera…", "En attente de l'appareil…",
                // Page Recettes
                "Search recipes...", "Rechercher une recette...",
                "New Recipe", "Nouvelle recette",
                "New video recipe", "Nouvelle recette vidéo",
                "No video recipe yet", "Aucune recette vidéo pour l'instant",
                "Press \"New video recipe\" to write one. Movie settings are set by hand in the camera's own menus: the X-T30 does not store them in the C1-C7 banks.",
                    "Appuyez sur « Nouvelle recette vidéo » pour en écrire une. Les réglages du mode film se saisissent à la main dans les menus du boîtier : le X-T30 ne les range pas dans les banques C1-C7.",
                "All simulations", "Toutes les simulations",
                "All", "Toutes",
                "Compatible", "Compatibles",
                "Favorites", "Favorites",
                "Imported", "Importées",
                "Local", "Locales",
                "Photo", "Photo",
                "Video", "Vidéo",
                "B&W", "N&B",
                "Color", "Couleur",
                "Portrait", "Portrait",
                "Street", "Rue",
                "Night", "Nuit",
                "Vintage", "Vintage",
                "Cinematic", "Cinéma",
                "Travel", "Voyage",
                "No recipes found", "Aucune recette trouvée",
                "Try a different search or filter, or create a new recipe.", "Essayez une autre recherche ou un autre filtre, ou créez une recette.",
                "{0} shown", "{0} affichées",
                "{0} of {1} shown", "{0} sur {1} affichées",
                "Show more recipes", "Afficher plus de recettes",
                "{0} LOCAL (yours, editable)", "{0} LOCALES (les vôtres, modifiables)",
                "{0} VIDEO", "{0} VIDÉO",
                "{0} imported and read-only from {1}", "{0} importées en lecture seule depuis {1}",
                "Recent Recipes", "Recettes récentes",
                "LOCAL LIBRARY", "BIBLIOTHÈQUE LOCALE",
                "View all", "Tout voir",
                // Compatibilité
                "✓  X-T30 Compatible", "✓  Compatible X-T30",
                "✕  Incompatible with X-T30", "✕  Incompatible avec le X-T30",
                "?  Compatibility unverified", "?  Compatibilité non vérifiée",
                "!  Partially compatible with X-T30", "!  Partiellement compatible X-T30",
                // Banques
                "Read my camera", "Lire mon appareil",
                "Load recipes into C1-C7…", "Charger des recettes dans C1-C7…",
                "Camera Custom Settings", "Banques personnalisées",
                "READ FROM CAMERA · {0} · {1}", "LU DANS L'APPAREIL · {0} · {1}",
                "LOCAL DEMONSTRATION", "DÉMONSTRATION LOCALE",
                "CAMERA", "APPAREIL",
                "LOCAL", "LOCAL",
                "matches \"{0}\" in library", "correspond à « {0} » dans la bibliothèque",
                // Deux lignes courtes : l'encart n'est pas assez haut pour davantage.
                "This application only reads the camera. It never sends a write command.\nA new settings file is loaded by Fujifilm's own Tether App.",
                    "Cette application ne fait que lire l'appareil.\nL'écriture est faite par la Tether App de Fujifilm.",
                "This application never writes to the camera. Fujifilm's own Tether App performs the restore.",
                    "Cette application n'écrit jamais dans l'appareil. La restauration est faite par la Tether App de Fujifilm.",
                // Plan des banques
                "Load recipes into C1-C7", "Charger des recettes dans C1-C7",
                "Choose what goes into each bank", "Choisissez le contenu de chaque banque",
                "One file sets all seven banks, so the camera is updated in a single restore. Values the settings file cannot hold are listed afterwards.",
                    "Un seul fichier règle les sept banques : l'appareil est mis à jour en une seule restauration. Les valeurs que le fichier ne peut pas contenir sont listées ensuite.",
                "— leave this bank unchanged —", "— laisser cette banque inchangée —",
                "Pick a recipe per bank. One file updates all seven at once.", "Une recette par banque. Un seul fichier met les sept à jour.",
                "Reset", "Réinitialiser",
                "Reading your camera", "Lecture de votre appareil",
                "Copying the settings file from the X-T30…", "Copie du fichier de réglages depuis le X-T30…",
                "Decoding the seven banks…", "Décodage des sept banques…",
                "Sending to your camera", "Envoi vers votre appareil",
                "Opening the Fujifilm Tether App…", "Ouverture de la Tether App Fujifilm…",
                "Re-reading the banks the camera now holds…", "Relecture des banques désormais dans l'appareil…",
                "Starting…", "Démarrage…",
                "Loading your recipes…", "Chargement de vos recettes…",
                "Loading the imported recipe catalogues…", "Chargement des catalogues importés…",
                "Reading the decoded camera banks…", "Lecture des banques décodées…",
                "{0} recipes ready", "{0} recettes prêtes",
                "now: {0}", "actuel : {0}",
                "{0}   ·   yours", "{0}   ·   à vous",
                "Send all seven to the camera", "Envoyer les sept à l'appareil",
                "Only create the file…", "Créer seulement le fichier…",
                "Cancel", "Annuler",
                "No bank selected yet. Pick at least one recipe.", "Aucune banque sélectionnée. Choisissez au moins une recette.",
                "{0} bank(s) will change; the other {1} and every other camera setting stay exactly as they are.",
                    "{0} banque(s) vont changer ; les {1} autres et tous les autres réglages restent intacts.",
                "{0} name(s) are longer than {1} characters and will be shortened by the camera.",
                    "{0} nom(s) dépassent {1} caractères et seront tronqués par l'appareil.",
                // Éditeur
                "Create a recipe", "Créer une recette",
                "Edit recipe", "Modifier la recette",
                "New recipe", "Nouvelle recette",
                "Only values your X-T30 actually accepts are offered. Stored on this computer; sending is a separate step.",
                    "Seules les valeurs que votre X-T30 accepte réellement sont proposées. Tout est stocké sur cet ordinateur ; l'envoi est une étape distincte.",
                "Name", "Nom",
                "Category", "Catégorie",
                "This recipe is for", "Cette recette est pour",
                "Photo — camera bank C1-C7", "Photo — banque C1-C7",
                "Video — movie mode", "Vidéo — mode film",
                "Choose photo…", "Choisir une photo…",
                "Save recipe", "Enregistrer la recette",
                "{0} of {1} settings will be written into the camera bank.", "{0} réglages sur {1} seront écrits dans la banque.",
                "Bank name on the camera:  \"{0}\"   ({1}/{2} characters)", "Nom de la banque sur l'appareil :  « {0} »   ({1}/{2} caractères)",
                "{0} of {1} movie settings filled in.", "{0} réglages vidéo sur {1} renseignés.",
                "Set in the camera's movie menus — never written to a C1-C7 bank.", "À régler dans les menus vidéo du boîtier — jamais écrit dans une banque C1-C7.",
                "Please enter a recipe name.", "Veuillez saisir un nom de recette.",
                "Name required", "Nom obligatoire",
                // Fiche recette
                "Edit local recipe", "Modifier la recette",
                "View article", "Voir l'article",
                "Write to camera", "Écrire dans l'appareil",
                "Compare with camera", "Comparer avec l'appareil",
                "SOURCE: CAMERA  ·  READ FROM YOUR X-T30", "SOURCE : APPAREIL  ·  LU DANS VOTRE X-T30",
                "SOURCE: LOCAL  ·  VIDEO RECIPE  ·  MOVIE MODE", "SOURCE : LOCAL  ·  RECETTE VIDÉO  ·  MODE FILM",
                "Movie recipe. The X-T30 keeps its movie image settings in its own menus, not in the C1-C7 banks and not in the settings file, so this one is set by hand on the camera.",
                    "Recette vidéo. Le X-T30 garde ses réglages d'image film dans ses propres menus, ni dans les banques C1-C7 ni dans le fichier de réglages : celle-ci se saisit à la main sur le boîtier.",
                "These settings all exist on the X-T30 in movie mode. Set them on the camera; nothing is written from here.",
                    "Tous ces réglages existent sur le X-T30 en mode film. Saisissez-les sur le boîtier ; rien n'est écrit d'ici.",
                "These parameters are compatible with the X-T30 feature set. Camera transfer remains disabled.",
                    "Ces paramètres sont compatibles avec le X-T30. Cette application n'écrit pas dans l'appareil.",
                "Stored on this computer only.", "Stocké uniquement sur cet ordinateur.",
                "Read from your camera's settings file. Only what that file stores is shown; ISO, WB shift and exposure are not in it and stay unspecified.",
                    "Lu dans le fichier de réglages de votre appareil. Seul ce que ce fichier contient est affiché ; l'ISO, le décalage de balance des blancs et l'exposition n'y sont pas et restent non précisés.",
                // Noms de réglages
                "ISO", "Sensibilité ISO",
                "Dynamic Range", "Plage dynamique",
                "Dynamic Range Priority", "Priorité plage D",
                "Film Simulation", "Simulation de film",
                "Monochromatic Color", "Couleur monochrome",
                "Grain Effect", "Effet de grain",
                "Color Chrome Effect", "Effet Color Chrome",
                "White Balance", "Balance des blancs",
                "WB Shift R", "Décalage BdB R",
                "WB Shift B", "Décalage BdB B",
                "Highlight", "Ton lumière",
                "Shadow", "Ton ombre",
                "Sharpness", "Netteté",
                "Noise Reduction", "Réduction du bruit",
                "Movie Mode", "Mode film",
                "F-Log", "F-Log",
                "Not specified", "Non précisé",
                // Sauvegardes et réglages
                "Local library backups", "Sauvegardes de la bibliothèque locale",
                "Save a snapshot of your local recipes and favorites. This does not read or restore camera settings.",
                    "Enregistre un instantané de vos recettes et favoris locaux. Cela ne lit ni ne restaure aucun réglage de l'appareil.",
                "Back up local library", "Sauvegarder la bibliothèque",
                "Open backups folder", "Ouvrir le dossier",
                "No local backups yet.", "Aucune sauvegarde pour l'instant.",
                "Application settings", "Réglages de l'application",
                "Appearance", "Apparence",
                "Language", "Langue",
                "Camera access", "Accès à l'appareil",
                "Read only — always enforced by the engine", "Lecture seule — imposée par le moteur",
                "Extended property scan (existing --sweep)", "Analyse étendue des propriétés (--sweep)",
                "Extended scanning uses the existing property sweep. It takes longer and does not enable any camera writes.",
                    "L'analyse étendue balaie toutes les propriétés. Elle est plus longue et n'autorise aucune écriture.",
                "Show the tutorial again", "Revoir le didacticiel",
                // Didacticiel
                "Tutorial", "Didacticiel",
                "Welcome", "Bienvenue",
                "Back", "Précédent",
                "Next", "Suivant",
                "Finish", "Terminer",
                "Skip", "Passer",
                "Do not show this again", "Ne plus afficher",
                "Step {0} of {1}", "Étape {0} sur {1}",
                // Messages
                "Camera read", "Lecture effectuée",
                "The camera was not read", "L'appareil n'a pas été lu",
                "The seven banks were read from your X-T30 and decoded.", "Les sept banques ont été lues dans votre X-T30 et décodées.",
                "Done", "Terminé",
                "Not sent", "Non envoyé",
                "Send to the camera", "Envoyer à l'appareil",
                "File ready", "Fichier prêt",
                "The file was not created", "Le fichier n'a pas été créé",
                "Read the camera first", "Lisez d'abord l'appareil",
            });
        }

        static Dictionary<string, string> Spanish()
        {
            return Build(new string[] {
                "Camera", "Cámara",
                "Recipes", "Recetas",
                "Camera Slots", "Bancos C1-C7",
                "Packs", "Packs",
                "Backups", "Copias de seguridad",
                "Diagnostics", "Diagnóstico",
                "Settings", "Ajustes",
                "READ ONLY", "SOLO LECTURA",
                "View Diagnostics", "Ver diagnóstico",
                "Last scan: {0}", "Última lectura: {0}",
                "Waiting for camera…", "Esperando la cámara…",
                "Search recipes...", "Buscar recetas...",
                "New Recipe", "Nueva receta",
                "All simulations", "Todas las simulaciones",
                "All", "Todas",
                "Compatible", "Compatibles",
                "Favorites", "Favoritas",
                "Imported", "Importadas",
                "Local", "Locales",
                "Photo", "Foto",
                "Video", "Vídeo",
                "B&W", "B/N",
                "Color", "Color",
                "Portrait", "Retrato",
                "Street", "Calle",
                "Night", "Noche",
                "Vintage", "Vintage",
                "Cinematic", "Cine",
                "Travel", "Viaje",
                "No recipes found", "No se encontraron recetas",
                "Try a different search or filter, or create a new recipe.", "Pruebe otra búsqueda u otro filtro, o cree una receta.",
                "{0} shown", "{0} mostradas",
                "{0} LOCAL (yours, editable)", "{0} LOCALES (suyas, editables)",
                "{0} VIDEO", "{0} VÍDEO",
                "{0} imported and read-only from {1}", "{0} importadas y de solo lectura desde {1}",
                "Recent Recipes", "Recetas recientes",
                "LOCAL LIBRARY", "BIBLIOTECA LOCAL",
                "View all", "Ver todas",
                "✓  X-T30 Compatible", "✓  Compatible con X-T30",
                "✕  Incompatible with X-T30", "✕  Incompatible con X-T30",
                "?  Compatibility unverified", "?  Compatibilidad sin verificar",
                "!  Partially compatible with X-T30", "!  Parcialmente compatible con X-T30",
                "Read my camera", "Leer mi cámara",
                "Load recipes into C1-C7…", "Cargar recetas en C1-C7…",
                "Camera Custom Settings", "Bancos personalizados",
                "READ FROM CAMERA · {0} · {1}", "LEÍDO DE LA CÁMARA · {0} · {1}",
                "LOCAL DEMONSTRATION", "DEMOSTRACIÓN LOCAL",
                "CAMERA", "CÁMARA",
                "LOCAL", "LOCAL",
                "matches \"{0}\" in library", "coincide con «{0}» en la biblioteca",
                "This application only reads the camera. It never sends a write command.\nA new settings file is loaded by Fujifilm's own Tether App.",
                    "Esta aplicación solo lee la cámara. Nunca envía una orden de escritura.\nEl nuevo archivo de ajustes lo carga la Tether App de Fujifilm.",
                "This application never writes to the camera. Fujifilm's own Tether App performs the restore.",
                    "Esta aplicación nunca escribe en la cámara. La restauración la realiza la Tether App de Fujifilm.",
                "Load recipes into C1-C7", "Cargar recetas en C1-C7",
                "Choose what goes into each bank", "Elija el contenido de cada banco",
                "One file sets all seven banks, so the camera is updated in a single restore. Values the settings file cannot hold are listed afterwards.",
                    "Un solo archivo ajusta los siete bancos: la cámara se actualiza en una única restauración. Los valores que el archivo no puede guardar se listan después.",
                "— leave this bank unchanged —", "— dejar este banco sin cambios —",
                "now: {0}", "actual: {0}",
                "{0}   ·   yours", "{0}   ·   suya",
                "Send all seven to the camera", "Enviar los siete a la cámara",
                "Only create the file…", "Solo crear el archivo…",
                "Cancel", "Cancelar",
                "No bank selected yet. Pick at least one recipe.", "Ningún banco seleccionado. Elija al menos una receta.",
                "{0} bank(s) will change; the other {1} and every other camera setting stay exactly as they are.",
                    "{0} banco(s) cambiarán; los otros {1} y todos los demás ajustes quedan intactos.",
                "{0} name(s) are longer than {1} characters and will be shortened by the camera.",
                    "{0} nombre(s) superan {1} caracteres y la cámara los acortará.",
                "Create a recipe", "Crear una receta",
                "Edit recipe", "Editar receta",
                "New recipe", "Nueva receta",
                "Only values your X-T30 actually accepts are offered. Stored on this computer; sending is a separate step.",
                    "Solo se ofrecen valores que su X-T30 acepta realmente. Se guarda en este ordenador; el envío es un paso aparte.",
                "Name", "Nombre",
                "Category", "Categoría",
                "This recipe is for", "Esta receta es para",
                "Photo — camera bank C1-C7", "Foto — banco C1-C7",
                "Video — movie mode", "Vídeo — modo película",
                "Choose photo…", "Elegir foto…",
                "Save recipe", "Guardar receta",
                "{0} of {1} settings will be written into the camera bank.", "Se escribirán {0} de {1} ajustes en el banco.",
                "Bank name on the camera:  \"{0}\"   ({1}/{2} characters)", "Nombre del banco en la cámara: «{0}»   ({1}/{2} caracteres)",
                "{0} of {1} movie settings filled in.", "{0} de {1} ajustes de vídeo rellenados.",
                "Set in the camera's movie menus — never written to a C1-C7 bank.", "Se ajusta en los menús de vídeo de la cámara, nunca se escribe en un banco C1-C7.",
                "Please enter a recipe name.", "Introduzca un nombre de receta.",
                "Name required", "Nombre obligatorio",
                "Edit local recipe", "Editar receta",
                "View article", "Ver artículo",
                "Write to camera", "Escribir en la cámara",
                "Compare with camera", "Comparar con la cámara",
                "SOURCE: CAMERA  ·  READ FROM YOUR X-T30", "ORIGEN: CÁMARA  ·  LEÍDO DE SU X-T30",
                "SOURCE: LOCAL  ·  VIDEO RECIPE  ·  MOVIE MODE", "ORIGEN: LOCAL  ·  RECETA DE VÍDEO  ·  MODO PELÍCULA",
                "Stored on this computer only.", "Guardado solo en este ordenador.",
                "ISO", "Sensibilidad ISO",
                "Dynamic Range", "Rango dinámico",
                "Dynamic Range Priority", "Prioridad de rango D",
                "Film Simulation", "Simulación de película",
                "Monochromatic Color", "Color monocromático",
                "Grain Effect", "Efecto de grano",
                "Color Chrome Effect", "Efecto Color Chrome",
                "White Balance", "Balance de blancos",
                "WB Shift R", "Desviación BB R",
                "WB Shift B", "Desviación BB B",
                "Highlight", "Tono de luces",
                "Shadow", "Tono de sombras",
                "Sharpness", "Nitidez",
                "Noise Reduction", "Reducción de ruido",
                "Movie Mode", "Modo película",
                "Not specified", "Sin especificar",
                "Local library backups", "Copias de la biblioteca local",
                "Back up local library", "Copiar la biblioteca",
                "Open backups folder", "Abrir la carpeta",
                "No local backups yet.", "Aún no hay copias.",
                "Application settings", "Ajustes de la aplicación",
                "Appearance", "Apariencia",
                "Language", "Idioma",
                "Camera access", "Acceso a la cámara",
                "Read only — always enforced by the engine", "Solo lectura — impuesto por el motor",
                "Show the tutorial again", "Ver el tutorial otra vez",
                "Tutorial", "Tutorial",
                "Welcome", "Bienvenido",
                "Back", "Atrás",
                "Next", "Siguiente",
                "Finish", "Terminar",
                "Skip", "Omitir",
                "Do not show this again", "No volver a mostrar",
                "Step {0} of {1}", "Paso {0} de {1}",
                "Camera read", "Lectura realizada",
                "The camera was not read", "No se pudo leer la cámara",
                "Done", "Hecho",
                "Cancel", "Cancelar",
            });
        }

        static Dictionary<string, string> German()
        {
            return Build(new string[] {
                "Camera", "Kamera",
                "Recipes", "Rezepte",
                "Camera Slots", "Speicher C1-C7",
                "Packs", "Packs",
                "Backups", "Sicherungen",
                "Diagnostics", "Diagnose",
                "Settings", "Einstellungen",
                "READ ONLY", "NUR LESEN",
                "View Diagnostics", "Diagnose ansehen",
                "Last scan: {0}", "Letzte Auslesung: {0}",
                "Waiting for camera…", "Warte auf die Kamera…",
                "Search recipes...", "Rezepte suchen...",
                "New Recipe", "Neues Rezept",
                "All simulations", "Alle Simulationen",
                "All", "Alle",
                "Compatible", "Kompatibel",
                "Favorites", "Favoriten",
                "Imported", "Importiert",
                "Local", "Lokal",
                "Photo", "Foto",
                "Video", "Video",
                "B&W", "S/W",
                "Color", "Farbe",
                "Portrait", "Porträt",
                "Street", "Street",
                "Night", "Nacht",
                "Vintage", "Vintage",
                "Cinematic", "Kino",
                "Travel", "Reise",
                "No recipes found", "Keine Rezepte gefunden",
                "Try a different search or filter, or create a new recipe.", "Versuchen Sie eine andere Suche oder einen anderen Filter, oder legen Sie ein Rezept an.",
                "{0} shown", "{0} angezeigt",
                "{0} LOCAL (yours, editable)", "{0} LOKAL (Ihre, bearbeitbar)",
                "{0} VIDEO", "{0} VIDEO",
                "{0} imported and read-only from {1}", "{0} importiert und schreibgeschützt von {1}",
                "Recent Recipes", "Zuletzt verwendet",
                "LOCAL LIBRARY", "LOKALE BIBLIOTHEK",
                "View all", "Alle ansehen",
                "✓  X-T30 Compatible", "✓  X-T30-kompatibel",
                "✕  Incompatible with X-T30", "✕  Nicht mit X-T30 kompatibel",
                "?  Compatibility unverified", "?  Kompatibilität ungeprüft",
                "!  Partially compatible with X-T30", "!  Teilweise X-T30-kompatibel",
                "Read my camera", "Kamera auslesen",
                "Load recipes into C1-C7…", "Rezepte in C1-C7 laden…",
                "Camera Custom Settings", "Individualspeicher",
                "READ FROM CAMERA · {0} · {1}", "AUS DER KAMERA GELESEN · {0} · {1}",
                "LOCAL DEMONSTRATION", "LOKALE DEMONSTRATION",
                "CAMERA", "KAMERA",
                "LOCAL", "LOKAL",
                "matches \"{0}\" in library", "entspricht „{0}“ in der Bibliothek",
                "This application only reads the camera. It never sends a write command.\nA new settings file is loaded by Fujifilm's own Tether App.",
                    "Diese Anwendung liest die Kamera nur. Sie sendet nie einen Schreibbefehl.\nEine neue Einstellungsdatei wird von Fujifilms Tether App geladen.",
                "This application never writes to the camera. Fujifilm's own Tether App performs the restore.",
                    "Diese Anwendung schreibt nie in die Kamera. Die Wiederherstellung übernimmt Fujifilms Tether App.",
                "Load recipes into C1-C7", "Rezepte in C1-C7 laden",
                "Choose what goes into each bank", "Wählen Sie den Inhalt jedes Speichers",
                "One file sets all seven banks, so the camera is updated in a single restore. Values the settings file cannot hold are listed afterwards.",
                    "Eine Datei setzt alle sieben Speicher: die Kamera wird in einer einzigen Wiederherstellung aktualisiert. Werte, die die Datei nicht speichern kann, werden danach aufgelistet.",
                "— leave this bank unchanged —", "— diesen Speicher unverändert lassen —",
                "now: {0}", "jetzt: {0}",
                "{0}   ·   yours", "{0}   ·   Ihre",
                "Send all seven to the camera", "Alle sieben an die Kamera senden",
                "Only create the file…", "Nur die Datei erstellen…",
                "Cancel", "Abbrechen",
                "No bank selected yet. Pick at least one recipe.", "Noch kein Speicher gewählt. Wählen Sie mindestens ein Rezept.",
                "{0} bank(s) will change; the other {1} and every other camera setting stay exactly as they are.",
                    "{0} Speicher ändern sich; die anderen {1} und alle übrigen Kameraeinstellungen bleiben unverändert.",
                "{0} name(s) are longer than {1} characters and will be shortened by the camera.",
                    "{0} Name(n) sind länger als {1} Zeichen und werden von der Kamera gekürzt.",
                "Create a recipe", "Rezept anlegen",
                "Edit recipe", "Rezept bearbeiten",
                "New recipe", "Neues Rezept",
                "Only values your X-T30 actually accepts are offered. Stored on this computer; sending is a separate step.",
                    "Es werden nur Werte angeboten, die Ihre X-T30 wirklich akzeptiert. Speicherung auf diesem Rechner; das Senden ist ein eigener Schritt.",
                "Name", "Name",
                "Category", "Kategorie",
                "This recipe is for", "Dieses Rezept ist für",
                "Photo — camera bank C1-C7", "Foto — Speicher C1-C7",
                "Video — movie mode", "Video — Filmmodus",
                "Choose photo…", "Foto wählen…",
                "Save recipe", "Rezept speichern",
                "{0} of {1} settings will be written into the camera bank.", "{0} von {1} Einstellungen werden in den Speicher geschrieben.",
                "Bank name on the camera:  \"{0}\"   ({1}/{2} characters)", "Speichername in der Kamera: „{0}“   ({1}/{2} Zeichen)",
                "{0} of {1} movie settings filled in.", "{0} von {1} Videoeinstellungen ausgefüllt.",
                "Set in the camera's movie menus — never written to a C1-C7 bank.", "Wird in den Filmmenüs der Kamera gesetzt — nie in einen C1-C7-Speicher geschrieben.",
                "Please enter a recipe name.", "Bitte geben Sie einen Rezeptnamen ein.",
                "Name required", "Name erforderlich",
                "Edit local recipe", "Rezept bearbeiten",
                "View article", "Artikel ansehen",
                "Write to camera", "In die Kamera schreiben",
                "Compare with camera", "Mit der Kamera vergleichen",
                "SOURCE: CAMERA  ·  READ FROM YOUR X-T30", "QUELLE: KAMERA  ·  AUS IHRER X-T30 GELESEN",
                "SOURCE: LOCAL  ·  VIDEO RECIPE  ·  MOVIE MODE", "QUELLE: LOKAL  ·  VIDEOREZEPT  ·  FILMMODUS",
                "Stored on this computer only.", "Nur auf diesem Rechner gespeichert.",
                "ISO", "ISO-Empfindlichkeit",
                "Dynamic Range", "Dynamikbereich",
                "Dynamic Range Priority", "Dynamikbereich-Priorität",
                "Film Simulation", "Filmsimulation",
                "Monochromatic Color", "Monochrome Farbe",
                "Grain Effect", "Körnungseffekt",
                "Color Chrome Effect", "Color-Chrome-Effekt",
                "White Balance", "Weißabgleich",
                "WB Shift R", "WA-Verschiebung R",
                "WB Shift B", "WA-Verschiebung B",
                "Highlight", "Lichter",
                "Shadow", "Schatten",
                "Sharpness", "Schärfe",
                "Noise Reduction", "Rauschreduzierung",
                "Movie Mode", "Filmmodus",
                "Not specified", "Nicht angegeben",
                "Local library backups", "Sicherungen der lokalen Bibliothek",
                "Back up local library", "Bibliothek sichern",
                "Open backups folder", "Ordner öffnen",
                "No local backups yet.", "Noch keine Sicherungen.",
                "Application settings", "Anwendungseinstellungen",
                "Appearance", "Darstellung",
                "Language", "Sprache",
                "Camera access", "Kamerazugriff",
                "Read only — always enforced by the engine", "Nur Lesen — vom Modul erzwungen",
                "Show the tutorial again", "Tutorial erneut anzeigen",
                "Tutorial", "Tutorial",
                "Welcome", "Willkommen",
                "Back", "Zurück",
                "Next", "Weiter",
                "Finish", "Fertig",
                "Skip", "Überspringen",
                "Do not show this again", "Nicht mehr anzeigen",
                "Step {0} of {1}", "Schritt {0} von {1}",
                "Camera read", "Kamera ausgelesen",
                "The camera was not read", "Die Kamera wurde nicht ausgelesen",
                "Done", "Fertig",
            });
        }

        static Dictionary<string, string> Italian()
        {
            return Build(new string[] {
                "Camera", "Fotocamera",
                "Recipes", "Ricette",
                "Camera Slots", "Banchi C1-C7",
                "Packs", "Pack",
                "Backups", "Backup",
                "Diagnostics", "Diagnostica",
                "Settings", "Impostazioni",
                "READ ONLY", "SOLA LETTURA",
                "View Diagnostics", "Vedi la diagnostica",
                "Last scan: {0}", "Ultima lettura: {0}",
                "Waiting for camera…", "In attesa della fotocamera…",
                "Search recipes...", "Cerca ricette...",
                "New Recipe", "Nuova ricetta",
                "All simulations", "Tutte le simulazioni",
                "All", "Tutte",
                "Compatible", "Compatibili",
                "Favorites", "Preferite",
                "Imported", "Importate",
                "Local", "Locali",
                "Photo", "Foto",
                "Video", "Video",
                "B&W", "B/N",
                "Color", "Colore",
                "Portrait", "Ritratto",
                "Street", "Street",
                "Night", "Notte",
                "Vintage", "Vintage",
                "Cinematic", "Cinema",
                "Travel", "Viaggio",
                "No recipes found", "Nessuna ricetta trovata",
                "Try a different search or filter, or create a new recipe.", "Prova un'altra ricerca o un altro filtro, oppure crea una ricetta.",
                "{0} shown", "{0} mostrate",
                "{0} LOCAL (yours, editable)", "{0} LOCALI (tue, modificabili)",
                "{0} VIDEO", "{0} VIDEO",
                "{0} imported and read-only from {1}", "{0} importate e in sola lettura da {1}",
                "Recent Recipes", "Ricette recenti",
                "LOCAL LIBRARY", "LIBRERIA LOCALE",
                "View all", "Vedi tutte",
                "✓  X-T30 Compatible", "✓  Compatibile X-T30",
                "✕  Incompatible with X-T30", "✕  Non compatibile con X-T30",
                "?  Compatibility unverified", "?  Compatibilità non verificata",
                "!  Partially compatible with X-T30", "!  Parzialmente compatibile X-T30",
                "Read my camera", "Leggi la fotocamera",
                "Load recipes into C1-C7…", "Carica ricette in C1-C7…",
                "Camera Custom Settings", "Banchi personalizzati",
                "READ FROM CAMERA · {0} · {1}", "LETTO DALLA FOTOCAMERA · {0} · {1}",
                "LOCAL DEMONSTRATION", "DIMOSTRAZIONE LOCALE",
                "CAMERA", "FOTOCAMERA",
                "LOCAL", "LOCALE",
                "matches \"{0}\" in library", "corrisponde a «{0}» nella libreria",
                "This application only reads the camera. It never sends a write command.\nA new settings file is loaded by Fujifilm's own Tether App.",
                    "Questa applicazione legge soltanto la fotocamera. Non invia mai un comando di scrittura.\nIl nuovo file di impostazioni viene caricato dalla Tether App di Fujifilm.",
                "This application never writes to the camera. Fujifilm's own Tether App performs the restore.",
                    "Questa applicazione non scrive mai nella fotocamera. Il ripristino è eseguito dalla Tether App di Fujifilm.",
                "Load recipes into C1-C7", "Carica ricette in C1-C7",
                "Choose what goes into each bank", "Scegli il contenuto di ogni banco",
                "One file sets all seven banks, so the camera is updated in a single restore. Values the settings file cannot hold are listed afterwards.",
                    "Un solo file imposta tutti e sette i banchi: la fotocamera si aggiorna con un unico ripristino. I valori che il file non può contenere sono elencati dopo.",
                "— leave this bank unchanged —", "— lascia questo banco invariato —",
                "now: {0}", "ora: {0}",
                "{0}   ·   yours", "{0}   ·   tua",
                "Send all seven to the camera", "Invia tutti e sette alla fotocamera",
                "Only create the file…", "Crea solo il file…",
                "Cancel", "Annulla",
                "No bank selected yet. Pick at least one recipe.", "Nessun banco selezionato. Scegli almeno una ricetta.",
                "{0} bank(s) will change; the other {1} and every other camera setting stay exactly as they are.",
                    "{0} banchi cambieranno; gli altri {1} e tutte le altre impostazioni restano intatti.",
                "{0} name(s) are longer than {1} characters and will be shortened by the camera.",
                    "{0} nomi superano {1} caratteri e la fotocamera li accorcerà.",
                "Create a recipe", "Crea una ricetta",
                "Edit recipe", "Modifica ricetta",
                "New recipe", "Nuova ricetta",
                "Only values your X-T30 actually accepts are offered. Stored on this computer; sending is a separate step.",
                    "Sono proposti solo i valori che la tua X-T30 accetta davvero. Tutto è salvato su questo computer; l'invio è un passaggio separato.",
                "Name", "Nome",
                "Category", "Categoria",
                "This recipe is for", "Questa ricetta è per",
                "Photo — camera bank C1-C7", "Foto — banco C1-C7",
                "Video — movie mode", "Video — modalità filmato",
                "Choose photo…", "Scegli una foto…",
                "Save recipe", "Salva la ricetta",
                "{0} of {1} settings will be written into the camera bank.", "{0} impostazioni su {1} saranno scritte nel banco.",
                "Bank name on the camera:  \"{0}\"   ({1}/{2} characters)", "Nome del banco sulla fotocamera: «{0}»   ({1}/{2} caratteri)",
                "{0} of {1} movie settings filled in.", "{0} impostazioni video su {1} compilate.",
                "Set in the camera's movie menus — never written to a C1-C7 bank.", "Da impostare nei menu video della fotocamera, mai scritto in un banco C1-C7.",
                "Please enter a recipe name.", "Inserisci un nome per la ricetta.",
                "Name required", "Nome obbligatorio",
                "Edit local recipe", "Modifica ricetta",
                "View article", "Vedi l'articolo",
                "Write to camera", "Scrivi nella fotocamera",
                "Compare with camera", "Confronta con la fotocamera",
                "SOURCE: CAMERA  ·  READ FROM YOUR X-T30", "ORIGINE: FOTOCAMERA  ·  LETTO DALLA TUA X-T30",
                "SOURCE: LOCAL  ·  VIDEO RECIPE  ·  MOVIE MODE", "ORIGINE: LOCALE  ·  RICETTA VIDEO  ·  MODALITÀ FILMATO",
                "Stored on this computer only.", "Salvato solo su questo computer.",
                "ISO", "Sensibilità ISO",
                "Dynamic Range", "Gamma dinamica",
                "Dynamic Range Priority", "Priorità gamma D",
                "Film Simulation", "Simulazione pellicola",
                "Monochromatic Color", "Colore monocromatico",
                "Grain Effect", "Effetto grana",
                "Color Chrome Effect", "Effetto Color Chrome",
                "White Balance", "Bilanciamento del bianco",
                "WB Shift R", "Scostamento BB R",
                "WB Shift B", "Scostamento BB B",
                "Highlight", "Tono alte luci",
                "Shadow", "Tono ombre",
                "Sharpness", "Nitidezza",
                "Noise Reduction", "Riduzione del rumore",
                "Movie Mode", "Modalità filmato",
                "Not specified", "Non specificato",
                "Local library backups", "Backup della libreria locale",
                "Back up local library", "Esegui il backup",
                "Open backups folder", "Apri la cartella",
                "No local backups yet.", "Ancora nessun backup.",
                "Application settings", "Impostazioni dell'applicazione",
                "Appearance", "Aspetto",
                "Language", "Lingua",
                "Camera access", "Accesso alla fotocamera",
                "Read only — always enforced by the engine", "Sola lettura — imposta dal motore",
                "Show the tutorial again", "Rivedi il tutorial",
                "Tutorial", "Tutorial",
                "Welcome", "Benvenuto",
                "Back", "Indietro",
                "Next", "Avanti",
                "Finish", "Fine",
                "Skip", "Salta",
                "Do not show this again", "Non mostrare più",
                "Step {0} of {1}", "Passo {0} di {1}",
                "Camera read", "Lettura eseguita",
                "The camera was not read", "La fotocamera non è stata letta",
                "Done", "Fatto",
            });
        }
    }
}
